### ISSUE TITLE
An "edit tasks file" button

### ISSUE THREAD

**Issue by lrem** [pkamenarsky/atea#24] opened 2012-02-22 14:53 UTC
It would be nice to have a button to edit the tasks file in the menu.

**Comment by pkamenarsky** [comment] 2012-02-22 14:55
This is a duplicate of this: https://github.com/pkamenarsky/atea/issues/9

**Closed as completed by pkamenarsky** 2012-02-22 14:55 UTC

**Comment by lrem** [comment] 2012-02-22 16:41
Ah, OK. However, it's not that easy to understand that description :P

**Comment by pkamenarsky** [comment] 2012-02-22 16:42
True, I'll change it :)
